-- Atlas quotation model — generated by scripts/etl/build.ts. Do not edit.

PRAGMA foreign_keys = ON;

CREATE TABLE region      (id TEXT PRIMARY KEY, name TEXT NOT NULL, slug TEXT NOT NULL);
CREATE TABLE country     (id TEXT PRIMARY KEY, name TEXT NOT NULL, slug TEXT NOT NULL,
                          region_id TEXT NOT NULL REFERENCES region(id),
                          iso3 TEXT, is_cluster INTEGER NOT NULL DEFAULT 0);
CREATE TABLE subregion   (id TEXT PRIMARY KEY, name TEXT NOT NULL,
                          region_id TEXT NOT NULL REFERENCES region(id));
CREATE TABLE state       (id TEXT PRIMARY KEY, name TEXT NOT NULL, slug TEXT NOT NULL,
                          country_id TEXT NOT NULL REFERENCES country(id),
                          subregion_id TEXT REFERENCES subregion(id));
CREATE TABLE place       (id TEXT PRIMARY KEY, name TEXT NOT NULL, slug TEXT NOT NULL,
                          country_id TEXT NOT NULL REFERENCES country(id),
                          state_id TEXT REFERENCES state(id),
                          has_rates INTEGER NOT NULL DEFAULT 0,
                          has_content INTEGER NOT NULL DEFAULT 0,
                          -- Resolved from map marker, primary airport or geocoder.
                          -- Null when no source could locate the place.
                          lat REAL, lon REAL);
CREATE TABLE place_alias (alias TEXT NOT NULL, place_id TEXT NOT NULL REFERENCES place(id),
                          source TEXT NOT NULL, how TEXT NOT NULL,
                          PRIMARY KEY (alias, source));

CREATE TABLE package     (id TEXT PRIMARY KEY, name TEXT NOT NULL, slug TEXT NOT NULL,
                          region_id TEXT NOT NULL REFERENCES region(id),
                          nights INTEGER NOT NULL, days INTEGER NOT NULL,
                          price_from_inr REAL NOT NULL,
                          flexible_duration INTEGER NOT NULL DEFAULT 0,
                          description TEXT, highlights TEXT);
-- A package may span several countries ("European Delights").
CREATE TABLE package_country (package_id TEXT NOT NULL REFERENCES package(id),
                          country_id TEXT NOT NULL REFERENCES country(id),
                          PRIMARY KEY (package_id, country_id));
CREATE TABLE package_state (package_id TEXT NOT NULL REFERENCES package(id),
                          state_id TEXT NOT NULL REFERENCES state(id),
                          PRIMARY KEY (package_id, state_id));
CREATE TABLE package_place (package_id TEXT NOT NULL REFERENCES package(id),
                          place_id TEXT NOT NULL REFERENCES place(id),
                          position INTEGER NOT NULL,
                          PRIMARY KEY (package_id, place_id));

CREATE TABLE destination (place_id TEXT PRIMARY KEY REFERENCES place(id),
                          destination_code TEXT, short_description TEXT, agent_summary TEXT,
                          currency TEXT, timezone TEXT,
                          min_nights INTEGER, ideal_nights INTEGER, max_nights INTEGER,
                          overall_cost_level TEXT);
CREATE TABLE suitability_score (place_id TEXT NOT NULL REFERENCES place(id),
                          category TEXT NOT NULL, score REAL NOT NULL,
                          PRIMARY KEY (place_id, category));
CREATE TABLE destination_tag (place_id TEXT NOT NULL REFERENCES place(id),
                          kind TEXT NOT NULL, tag TEXT NOT NULL,
                          PRIMARY KEY (place_id, kind, tag));
CREATE TABLE monthly_score (place_id TEXT NOT NULL REFERENCES place(id),
                          month INTEGER NOT NULL CHECK (month BETWEEN 1 AND 12),
                          weather REAL, crowd REAL, price REAL, overall REAL, recommendation TEXT,
                          PRIMARY KEY (place_id, month));
CREATE TABLE area        (id TEXT PRIMARY KEY, place_id TEXT NOT NULL REFERENCES place(id),
                          name TEXT NOT NULL, price_level TEXT, transport_convenience REAL,
                          zone TEXT NOT NULL);
CREATE TABLE attraction  (id TEXT PRIMARY KEY, place_id TEXT NOT NULL REFERENCES place(id),
                          name TEXT NOT NULL, priority REAL NOT NULL);
CREATE TABLE activity    (id TEXT PRIMARY KEY, place_id TEXT NOT NULL REFERENCES place(id),
                          code TEXT NOT NULL, name TEXT NOT NULL);
CREATE TABLE purpose_activity (place_id TEXT NOT NULL REFERENCES place(id),
                          purpose TEXT NOT NULL, description TEXT NOT NULL);
CREATE TABLE cluster     (id TEXT PRIMARY KEY, place_id TEXT NOT NULL REFERENCES place(id),
                          name TEXT NOT NULL, recommended_duration TEXT,
                          duration_hours REAL NOT NULL, walking_intensity TEXT);
CREATE TABLE cluster_attraction (cluster_id TEXT NOT NULL REFERENCES cluster(id),
                          name TEXT NOT NULL, position INTEGER NOT NULL,
                          PRIMARY KEY (cluster_id, position));

-- The 21 destination-file sections no structured table claims: airport
-- transfer logic, the per-audience travel guidance, the worked itinerary
-- patterns, the agent insights and the destination's own decision rules.
-- Captured whole, keyed by the section and the audience it is written for.
CREATE TABLE destination_guidance (
                          place_id TEXT NOT NULL REFERENCES place(id),
                          section INTEGER NOT NULL,
                          topic TEXT NOT NULL,
                          section_title TEXT NOT NULL,
                          heading TEXT,
                          audience TEXT,
                          body TEXT NOT NULL,
                          position INTEGER NOT NULL,
                          PRIMARY KEY (place_id, position));
CREATE TABLE destination_guidance_bullet (
                          place_id TEXT NOT NULL REFERENCES place(id),
                          position INTEGER NOT NULL,
                          bullet_index INTEGER NOT NULL,
                          text TEXT NOT NULL,
                          PRIMARY KEY (place_id, position, bullet_index));
CREATE INDEX idx_guidance_audience ON destination_guidance (audience);
CREATE INDEX idx_guidance_topic ON destination_guidance (topic);

-- Section 33 parsed into an evaluable form. One row per rule, with its
-- conditions and any executable effect in child tables.
CREATE TABLE decision_rule (
                          id TEXT PRIMARY KEY,
                          place_id TEXT NOT NULL REFERENCES place(id),
                          action TEXT NOT NULL,
                          reason TEXT);
CREATE TABLE decision_rule_condition (
                          rule_id TEXT NOT NULL REFERENCES decision_rule(id),
                          position INTEGER NOT NULL,
                          variable TEXT NOT NULL,
                          operator TEXT NOT NULL,
                          value TEXT NOT NULL,
                          number REAL,
                          unit TEXT,
                          -- How this condition joins the previous one.
                          joiner TEXT,
                          PRIMARY KEY (rule_id, position));
CREATE TABLE decision_rule_effect (
                          rule_id TEXT NOT NULL REFERENCES decision_rule(id),
                          position INTEGER NOT NULL,
                          kind TEXT NOT NULL,
                          token TEXT NOT NULL,
                          PRIMARY KEY (rule_id, position, token));
CREATE INDEX idx_rule_place ON decision_rule (place_id);
CREATE INDEX idx_rule_condition_var ON decision_rule_condition (variable);

CREATE TABLE hotel_rate  (place_id TEXT NOT NULL REFERENCES place(id),
                          star TEXT NOT NULL, zone TEXT NOT NULL, meal_plan TEXT NOT NULL,
                          inr REAL NOT NULL, baseline REAL, baseline_currency TEXT,
                          source TEXT NOT NULL,
                          PRIMARY KEY (place_id, star, zone, meal_plan));
CREATE TABLE transfer_rate (place_id TEXT NOT NULL REFERENCES place(id),
                          service TEXT NOT NULL, inr REAL NOT NULL,
                          baseline REAL, baseline_currency TEXT, source TEXT NOT NULL,
                          PRIMARY KEY (place_id, service));
CREATE TABLE meal_rate   (place_id TEXT NOT NULL REFERENCES place(id),
                          meal TEXT NOT NULL, inr REAL NOT NULL,
                          baseline REAL, baseline_currency TEXT, source TEXT NOT NULL,
                          PRIMARY KEY (place_id, meal));
CREATE TABLE activity_rate (place_id TEXT NOT NULL REFERENCES place(id),
                          code TEXT NOT NULL, unit TEXT, inr REAL NOT NULL,
                          baseline REAL, baseline_currency TEXT, source TEXT NOT NULL,
                          PRIMARY KEY (place_id, code));
CREATE TABLE markup_rule (level TEXT NOT NULL, rule TEXT NOT NULL, unit TEXT,
                          value REAL NOT NULL, notes TEXT,
                          PRIMARY KEY (level, rule));

CREATE TABLE route       (id TEXT PRIMARY KEY, scope TEXT NOT NULL, country_context TEXT,
                          origin_place_id TEXT, dest_place_id TEXT,
                          origin_country_id TEXT, dest_country_id TEXT,
                          onsite_mode TEXT, route_type TEXT);
CREATE TABLE route_option (route_id TEXT NOT NULL REFERENCES route(id),
                          mode TEXT NOT NULL, enabled INTEGER NOT NULL,
                          price_low REAL, price_high REAL, currency TEXT,
                          duration_minutes REAL, terminal_from TEXT, terminal_to TEXT,
                          unavailable_reason TEXT,
                          PRIMARY KEY (route_id, mode));

CREATE TABLE flight_band (id TEXT PRIMARY KEY, origin_city TEXT NOT NULL,
                          dest_country_id TEXT NOT NULL REFERENCES country(id),
                          carrier TEXT NOT NULL, cabin TEXT NOT NULL, trip_type TEXT NOT NULL,
                          price_low REAL NOT NULL, price_high REAL NOT NULL,
                          currency TEXT NOT NULL, duration_minutes REAL, source TEXT NOT NULL);
CREATE TABLE visa_rule   (nationality TEXT NOT NULL,
                          dest_country_id TEXT NOT NULL REFERENCES country(id),
                          requirement TEXT NOT NULL, fee_inr REAL NOT NULL,
                          processing_days INTEGER, source TEXT NOT NULL,
                          PRIMARY KEY (nationality, dest_country_id));
CREATE TABLE insurance_rate (zone TEXT PRIMARY KEY, per_person_per_day_inr REAL NOT NULL,
                          source TEXT NOT NULL);
CREATE TABLE city_tax    (place_id TEXT PRIMARY KEY REFERENCES place(id),
                          per_person_per_night_inr REAL NOT NULL, source TEXT NOT NULL);

CREATE INDEX idx_place_country      ON place(country_id);
CREATE INDEX idx_package_country    ON package_country(country_id);
CREATE INDEX idx_hotel_place        ON hotel_rate(place_id);
CREATE INDEX idx_activity_rate_place ON activity_rate(place_id);
CREATE INDEX idx_route_origin       ON route(origin_place_id);
CREATE INDEX idx_route_dest         ON route(dest_place_id);
CREATE INDEX idx_cluster_place      ON cluster(place_id);
CREATE INDEX idx_visa_nationality   ON visa_rule(nationality);
